# Generated by Django 4.1.5 on 2023-01-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fajr', models.TimeField()),
                ('sunrise', models.TimeField()),
                ('dhuhr', models.TimeField()),
                ('asr', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isha', models.TimeField()),
                ('date', models.DateField()),
                ('office_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_times', to='account.officelocation', verbose_name='Office Location')),
            ],
            options={
                'verbose_name': 'Prayer Time',
                'verbose_name_plural': 'Prayer Times',
            },
        ),
    ]
